spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8083

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.user=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=*

app.message=Hello
